const express = require('express');
const { authenticate } = require('../middleware/auth');
const { generateSolutionRecommendations } = require('../services/gemini');

const router = express.Router();
router.use(authenticate);

// ─── POST /api/solutions/generate ─────────────────────────────────────────────
// Accept a business context from the request body and return a structured
// implementation plan generated by Gemini AI
router.post('/generate', async (req, res) => {
  try {
    const {
      problem,          // e.g. "High customer churn in Tier-2 cities"
      businessType,     // e.g. "fashion retail"
      currentMetrics,   // optional: current KPIs
      goals,            // optional: desired outcomes
      constraints,      // optional: budget, team size, timeline
    } = req.body;

    if (!problem) {
      return res.status(400).json({ success: false, message: 'problem is required' });
    }

    const context = {
      problem,
      businessType: businessType || 'Indian retail',
      currentMetrics: currentMetrics || {},
      goals: goals || [],
      constraints: constraints || {},
    };

    const recommendations = await generateSolutionRecommendations(context);

    res.json({ success: true, data: recommendations });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

module.exports = router;
