const express = require('express');
const { authenticate } = require('../middleware/auth');
const { generateSolutionRecommendations } = require('../services/gemini');

const router = express.Router();
router.use(authenticate);

// ─── POST /api/solutions/generate ─────────────────────────────────────────────
// Accept a business context from the request body and return a structured
// implementation plan generated by Gemini AI
router.post('/generate', async (req, res) => {
  try {
    const {
      businessType,
      customerCount,
      monthlyOrders,
      challenges,
      problem // legacy fallback
    } = req.body;

    const context = {
      businessType: businessType || 'Indian retail',
      customerCount: customerCount || 0,
      monthlyOrders: monthlyOrders || 0,
      challenges: challenges || problem || 'General CRM implementation',
    };

    const recommendations = await generateSolutionRecommendations(context);

    res.json({ success: true, data: recommendations });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
});

module.exports = router;
